-- upgrade --
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created` DATETIME(6) NOT NULL,
    `name` VARCHAR(50) NOT NULL  DEFAULT '',
    `mobile` VARCHAR(50) NOT NULL  DEFAULT '',
    `age` INT NOT NULL  DEFAULT 0
) CHARACTER SET utf8mb4;
